sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  - BULLETIN_EDITION=2016

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7
    - php: hhvm
  allow_failures:
    - php: hhvm

before_install:
  - phpenv config-rm xdebug.ini || return 0
  - composer self-update

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - ./vendor/bin/phpunit
