sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  - BULLETIN_EDITION=2016

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_install:
  - phpenv config-rm xdebug.ini || return 0
  - composer self-update

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs --prefer-dist

script:
  - ./vendor/bin/phpunit
