<h1><?php echo $this->title; ?></h1>
<h2><?php echo $this->college; ?></h2>
<?php echo $this->minor_available; ?>
<?php echo $this->chief_advisor; ?>
<?php echo $this->description; ?>
<?php echo $this->admission; ?>
<?php echo $this->major_requirements; ?>
<?php echo $this->additional_major_requirements; ?>
<?php echo $this->college_degree_requirements; ?>
<?php echo $this->requirements_for_minor; ?>
<?php echo $this->ace_requirements; ?>
<?php echo $this->other; ?>